import fs from 'fs/promises';
import path from 'path';

async function generateTeamsFile() {
  try {
    const startDate = new Date('2026-03-19');
    const endDate = new Date('2026-03-24'); // March 19 through March 22 encompasses the Round of 64 and 32
    let teams = new Map();

    console.log("Fetching tournament games from ESPN...");

    for (let d = startDate; d <= endDate; d.setDate(d.getDate() + 1)) {
      const dateStr = d.toISOString().split('T')[0].replace(/-/g, '');
      const url = `https://site.api.espn.com/apis/site/v2/sports/basketball/mens-college-basketball/scoreboard?dates=${dateStr}&limit=100`;
      const res = await fetch(url);
      const data = await res.json();
      
      if (data.events) {
        data.events.forEach(event => {
          // ensure it's a postseason game (season type 3)
          if (event.season.type === 3) {
            const comps = event.competitions[0].competitors;
            comps.forEach(c => {
              if (!teams.has(c.team.id)) {
                teams.set(c.team.id, {
                  id: teams.size + 1,
                  name: c.team.displayName,
                  espnId: c.team.id,
                  logo: c.team.logo || null,
                  seed: c.curatedRank?.current || null, // ESPN sometimes has the seed here
                  wins: 0,
                  losses: 0,
                  eliminated: false
                });
              }
            });
          }
        });
      }
    }
    
    console.log(`Found ${teams.size} unique tournament teams.`);
    
    if (teams.size === 64) {
      const teamsArray = Array.from(teams.values());
      
      // Sort alphabetically for clean output
      teamsArray.sort((a, b) => a.name.localeCompare(b.name));
      
      // Re-assign IDs 1-64 based on alphabetical order for cleanliness
      teamsArray.forEach((t, i) => t.id = i + 1);

      const fileContent = `// This file was auto-generated by scripts/fetchTeams.js
// It contains the 64 tournament teams for the 2026 March Madness pool.

export const teams = ${JSON.stringify(teamsArray, null, 2)};
`;

      const outputPath = path.resolve(process.cwd(), 'src/data/teams.js');
      await fs.writeFile(outputPath, fileContent, 'utf-8');
      console.log(`Successfully generated ${outputPath}`);
    } else {
      console.error(`Error: Found ${teams.size} teams instead of exactly 64. Aborting file creation.`);
    }

  } catch (e) {
    console.error("Error generating teams file:", e);
  }
}

generateTeamsFile();
